config:
  docs_subdir: '_docs'
  raw_repo_url: 'https://raw.githubusercontent.com/marcinbiegun/creativecoding-sketches'
  repo_url: 'https://github.com/marcinbiegun/creativecoding-sketches'

root:
  text: |
    # creativecoding-sketches
    A collection of creative coding doodles.

    ## Most interesting works

softwares:
  KodeLife:
    name: 'KodeLife'
    dir: 'KodeLife'
  Processing:
    name: 'Vuo'
    dir: 'Vuo'
    projects_in_directories: true
  QuartzComposer:
    name: 'QuartzComposer'
    dir: 'QuartzComposer'
  TouchDesigner:
    name: 'TouchDesigner'
    dir: 'TouchDesigner'
    projects:
      tunnel.toe:
        pinned: true
      molecules.toe:
        text: |
          loops nicely
        pinned: true
      acid_shapes.toe:
        text: |
          goadupa 2017
  Vuo:
    text: |
      * `compositions` - standalone projects
      * `nodes` - Vuo modules, put them in in `~/Library/Application Support/Vuo/Modules`
      * `generators` - projects prepared to be embeded in other softwares, e.g. in VDMX
    name: 'Vuo'
    dir: 'Vuo'
    project_dirs:
      - 'compositions'
      - 'generators'
      - 'nodes'
