config:
  docs_subdir: '_docs'
  raw_repo_url: 'https://raw.githubusercontent.com/marcinbiegun/creativecoding-sketches'
  repo_url: 'https://github.com/marcinbiegun/creativecoding-sketches'

softwares:
  KodeLife:
    name: 'KodeLife'
    dir: 'KodeLife'
  Processing:
    name: 'Vuo'
    dir: 'Vuo'
    projects_in_directories: true
  QuartzComposer:
    name: 'QuartzComposer'
    dir: 'QuartzComposer'
  TouchDesigner:
    name: 'TouchDesigner'
    dir: 'TouchDesigner'
  Vuo:
    name: 'Vuo'
    dir: 'Vuo'
    project_dirs:
      - 'compositions'
      - 'generators'
      - 'nodes'
